[package]
name = "pcap-explore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.5"
pktparse = "0.7.1"
tls-parser = "0.11.0"
